### ISSUE TITLE
ImportError: No module named pytrustnfe.certificado

### ISSUE THREAD

**Issue by ahmedgenina** [Trust-Code/trust-docker#4]
Ola Equipe de Trust-code ,obrigado pra compartilhar esse trabalho ,  executei o Dockerfile que esta na pasta "odoo" mas terminei com o mensagem de erro abaixo, sera que esta faltando o "PyTrustNFe 0.1.7" nas dependências ? 

 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1296, in __call__
    self.load_addons()
  File "/opt/odoo/openerp/http.py", line 1317, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/mnt/extra-addons/eletronic-docs/nfse_sao_paulo/__init__.py", line 6, in <module>
    from . import models
  File "/mnt/extra-addons/eletronic-docs/nfse_sao_paulo/models/__init__.py", line 23, in <module>
    from . import base_nfse
  File "/mnt/extra-addons/eletronic-docs/nfse_sao_paulo/models/base_nfse.py", line 8, in <module>
    from pytrustnfe.certificado import Certificado
ImportError: No module named pytrustnfe.certificado

**Comment by danimaribeiro** [comment]
Esses docker são para utilização interna, não recomendamos a utilização do mesmo.

Mas respondendo a pergunta está faltando sim a instalação da lib pytrustnfe
sudo pip install pytrustnfe
